// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://armblanzbowvppzyvqad.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFybWJsYW56Ym93dnBwenl2cWFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2Njg5OTMsImV4cCI6MjA3MTI0NDk5M30.qNL3kQKaa66T_rxvWJOBWwH2PE71iDbaOxaUdvNK0OU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});